export const ApiConstants = {
  LOGIN: '/login',
  SIGN_UP: '/signup',
  PRE_VALIDATE_EMAIL: '/preValidateEmail/',
  PRE_VALIDATE_EMAIL_EDIT: '/preValidateEmailEdit/',
  GET_ALL_RESTAURANTS: '/restaurant',
  GET_RESTAURANT_BY_ID: '/restaurant/',
  GET_RESTAURANT_IMAGES: '/restaurant/images/',
  GET_RESTAURANTS_BY_LOCATION: '',
  SAVE_COMMENTS: '/review/',
  SAVE_COMMENTS_OWNER: '/review/owner/',
  GET_REVIEWS_BY_ID: '/review/',
  GET_PENDING_ACTIONS: '/review/getPendingActions',
  NEW_RESTAURANT: '/restaurant',
  GET_OWNED_RESTAURANTS: '/restaurant/getOwnedRestaurants',
  UPLOAD_IMAGE: '/restaurant/uploadImage/',
  SHOW_IMAGES: '/restaurant/showImages/',
  UPDATE_IMAGE: '/restaurant/updateImage/',
  DELETE_IMAGE: '/restaurant/deleteImage/',
  GET_USERS: '/user/getUsers',
  DELETE_USER: '/user/',
  GET_USER_DETAILS: '/user/getDetailedUser/',
  UPDATE_USER: '/user/',
  DELETE_RESTAURANT: '/restaurant/',
  UPDATE_RESTAURANT: '/restaurant/',
  DELETE_REVIEW: '/review/',
  UPDATE_REVIEW: '/review/update/'
};
